### ISSUE TITLE
issue list

### ISSUE THREAD

**Issue by gonsakon** [gonsakon/node-workshop#1]
1.移除node_modules
2.再寫一個getFileJson，當網頁重新載入時，可重新載入原本上傳的檔案list
3.請把檔案上傳的內容集中寫在router的page.js裡面集中管理，不能寫在app.js

**Comment by bbandydd** [comment]
三個問題：
1. 把檔案上傳那些移到page.js，require就必須寫在page.js，有辦法宣告在app.js然後傳過去嗎？
2. 檔案上傳移到page.js後，使用a link下載檔案就變成json格式的資訊，無法點選就下載。
3. 取得檔案列表我用fs.readdir，他是非同步的，所以我只能把res.render放在裡面，這樣可以嗎？

**Comment by gonsakon** [comment]
fb2d3d88415ce869917779baa865724a26f1ca80
close
